[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "peppermint"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "lark",
    "pandas",
    "scikit-learn",
    "umap-learn",
    "matplotlib",
    "seaborn",
]

[project.scripts]
pep = "peppermint.__main__:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["peppermint*"]
